### ISSUE TITLE
[Fix: 그룹 드롭다운] 그룹 목록 없을 때 드롭다운이 일부 펼쳐지는 현상 (우선순위: 하)

### ISSUE THREAD

**Issue by jin-ttao** [Team-Bloblow/Bloblow-Client#14]
문제: 그룹 목록 없을 때 드롭다운이 일부 펼쳐지는 현상
해결: 그룹 목록이 없다면 하단에 선도 표기되지 않도록 수정 필요
<img width="500" alt="image" src="https://github.com/user-attachments/assets/514c5c2a-a40d-44d0-94f3-c0c8e8a0c969">

**Comment by SsongQ-92** [comment]
![image](https://github.com/user-attachments/assets/d4bc8e62-b94a-4b42-ad92-bc17bef3ae12)

수정 완료
