### ISSUE TITLE
[Fix: 그룹 목록] 사용자의 그룹 목록이 없는 경우, 화면이 안나오는 문제

### ISSUE THREAD

**Issue by only-pine** [Team-Bloblow/Bloblow-Client#15]
### 문제 현상
- 로그인 후, 사용자가 만든 그룹이 없는 경우 빈 화면이 표시된다.

### 문제 발생 화면과 콘솔 메시지
<img width="1205" alt="스크린샷 2024-11-10 오후 10 59 48" src="https://github.com/user-attachments/assets/5b421ad9-00b5-472a-9efa-8adeeb06fc96">

**Comment by SsongQ-92** [comment]
이거는 현재 #13 PR 에 내용 있어요~! merge되면 확인 가능하십니다
